name: Test

on:
  pull_request:
    branches: [main, master]
  push:
    branches: [main, master]
    paths:
      - 'lib/**'
      - 'vite.config.ts'
      - 'vitest.config.ts'
      - 'package.json'
      - 'package-lock.json'
      - 'tsconfig*.json'

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.12.0
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run Unit Tests
        run: npx vitest run --exclude="**/bundle.test.ts" --exclude="**/distribution.test.ts"

      - name: Run Type Check
        run: npx tsc --noEmit

      - name: Run Linting
        run: npm run lint

      - name: Build and Test Bundle
        run: npm run test:bundle

      - name: Build and Test Distribution
        run: npm run test:distribution
